image: tico/docker

variables:
  DOCKER_HOST: "172.18.18.138:2375"

build:
  stage: build
  script:
    - "docker -H $DOCKER_HOST build -t registry.cn-hangzhou.aliyuncs.com/gosun/seemmo-algo-server:latest -f docker/seemmo_server/Dockerfile ."
    - "docker -H $DOCKER_HOST build -t registry.cn-hangzhou.aliyuncs.com/gosun/video-dispose:latest -f docker/video-dispose/Dockerfile ."
  only:
    - master
  tags:
    - gpu_docker