FROM nvidia/cuda:10.0-devel-ubuntu16.04 as builder

COPY FFmpeg /root/FFmpeg
COPY x264 /root/x264

WORKDIR /root

#编译x264
RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y curl pkg-config && \
    cd /root && \
    curl -O https://www.nasm.us/pub/nasm/releasebuilds/2.13.03/nasm-2.13.03.tar.gz && \
    tar -xzvf nasm-2.13.03.tar.gz && \
    cd /root/nasm-2.13.03 && \
    ./configure  --prefix=/usr &&\
    make -j$(nproc) && \
    make install && \
    git clone http://git.videolan.org/git/x264.git && \
    cd /root/x264 && \
    ./configure --enable-shared && \
    make -j$(nproc) && \
    make install

#编译FFmpeg    
RUN cd /root && \
    git clone -b n8.1.24.2 https://github.com/FFmpeg/nv-codec-headers.git && \
    cd /root/nv-codec-headers && \
    make install && \
    cd /root && \
    git clone -b n4.0.2 https://github.com/FFmpeg/FFmpeg.git && \
    cd /root/FFmpeg && \
    ./configure  --enable-gpl --enable-nvenc --enable-cuda --enable-cuvid --enable-nonfree --enable-libnpp --enable-libx264 --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 && \
    make -j$(nproc) && \
    make install 

#编译FFmpeg补丁
RUN cd /root && \
    git clone http://47.97.174.151:10080/service/video-dispose.git && \
    cd /root/video-dispose && \
    export FFMPEG_HOME='/root/FFmpeg' && \
    cd FFmpeg-patch && \
    sh build_ffmpeg.sh
