FROM grpc/cxx:latest as ORIGIN


FROM ubuntu:16.04 as BUILD
COPY --from=ORIGIN /var/local/git/grpc /var//local/git/grpc

RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list && \
    apt-get update && apt-get install -y \
      build-essential autoconf git pkg-config \
      automake libtool curl make g++ unzip && \
    apt-get autoclean && apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# install protobuf first, then grpc
ENV GRPC_RELEASE_TAG v1.15.x

RUN  rm -rf /usr/local/lib/* && \
    rm -rf /usr/local/include/* && \
    cd /var/local/git/grpc && \
    git checkout ${GRPC_RELEASE_TAG} && \
    git pull && \
    git submodule update  && \
    echo "--- installing protobuf ---" && \
    cd third_party/protobuf && \
    export CFLAGS=-fPIC && export CXXFLAGS=-fPIC &&  \
    ./autogen.sh && ./configure --disable-shared && \
    make clean && make -j$(nproc) && make install && make clean && ldconfig && \
    echo "--- installing grpc ---" && \
    cd /var/local/git/grpc && \
    make -j$(nproc) install-static && make install-headers && make install-plugins && make clean && ldconfig


