FROM ubuntu:16.04 as BUILD

RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list && \
    apt-get update && apt-get install -y \
      build-essential autoconf git pkg-config \
      automake libtool curl make g++ unzip cmake libssl-dev wget && \
    apt-get autoclean && apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


WORKDIR ~

ENV CFLAGS -fPIC
ENV CXXFLAGS -fPIC

RUN cd ~ && \
	wget zlib.net/zlib-1.2.11.tar.gz && \
	tar xzf zlib*.tar.gz && \
	cd zlib-* && \ 
	./configure --static && \
	make -j$(nproc) && \
	make install

RUN cd ~ && \
	git clone -b v2.2.1 https://github.com/gflags/gflags.git && \
	cd gflags && \
	mkdir build && cd build && cmake .. && make  -j$(nproc) && make install


RUN   cd ~ && \
   	git clone -b v3.6.1 https://github.com/google/protobuf.git && \
	cd protobuf && \
	./autogen.sh && \
	./configure --disable-shared && \
	 make -j$(nproc) && \
	 make install

RUN  cd ~ && \
  	git clone https://github.com/google/leveldb.git && \
	cd  leveldb && \
	sed -i 's/3.9/3.2/g' CMakeLists.txt && \
	mkdir build && cd build && cmake .. && make  -j$(nproc) && make install

RUN  cd ~ && \
  	git clone -v https://github.com/brpc/brpc.git && \ 
	cd brpc && \
	mkdir build && cd build && cmake .. -DBUILD_SHARED_LIBS=0 -DBUILD_STATIC_LIBS=1 -DWITH_DEBUG_SYMBOLS=OFF && make  -j$(nproc) && make install
