#------------ 算法sdk ------------
FROM registry.cn-hangzhou.aliyuncs.com/gosun/gosun_sdk:latest as gosun_sdk

#------------ 编译video-dispose ------------
FROM registry.cn-hangzhou.aliyuncs.com/gosun/brpc_opencv_ffmpeg:latest as base_builder

WORKDIR /root
ENV CFLAGS -fPIC
ENV CXXFLAGS -fPIC
ENV GOSUN_SDK_HOME /root/gosun_sdk
ENV FFMPEG_HOME /root/FFmpeg
ENV LC_ALL en_US.UTF-8
ENV LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${GOSUN_SDK_HOME}/lib

#拷贝算法sdk
COPY --from=gosun_sdk $GOSUN_SDK_HOME $GOSUN_SDK_HOME

RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list && \
    apt-get update --fix-missing && \
    apt-get install -y libssl-dev libfreetype6 libfreetype6-dev \
      locales libjasper1 libjasper-dev libdc1394-22 libavcodec-ffmpeg56 \
      libswscale-ffmpeg3 libavformat-ffmpeg56 libcairo2 libgdk-pixbuf2.0-0 \
      libgtk2.0-0 libopenexr22 libopenblas-base libopenblas-dev uuid-dev \
      libmpich12  libgoogle-glog-dev   liblmdb0 libleveldb1v5 libopenmpi1.10 && \
    apt-get autoclean && apt-get clean && \
    locale-gen $LC_ALL

ADD . /root/video-dispose
    
RUN cd /root/video-dispose && \
    cd FFmpeg-patch && \
    sh patch_ffmpeg.sh && \
    ##打补丁后重新编译ffmpeg
    cd /root/FFmpeg && \
    ./configure --enable-static --enable-gpl --enable-nvenc --enable-cuda --enable-cuvid --enable-nonfree --enable-libnpp --enable-libx264 --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 && \
    make -j$(nproc) && \
    make install && \
    ##编译video-dispose插件
    cd /root/video-dispose && \
    make -C algo/vendor/seemmo -j$(nproc) -B -f Makefile_stub install && \
    make -C algo/vendor/gosun -j$(nproc) -B -f Makefile_stub install && \
    make -C algo/stub -j$(nproc) -B install && \
    make -C vfilter -j$(nproc) -B install && \
    make -C vfilter install_font
    
    